version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/launcher"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
