'use strict';
const crypto=require('crypto');
const M=require('../public/assets/js/stream-maker-core');
async function initialize(pool){await pool.query(`CREATE TABLE IF NOT EXISTS creator_stream_maker (
 id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creator_accounts(id) ON DELETE CASCADE,
 config JSONB NOT NULL, version INTEGER NOT NULL DEFAULT 1, public_token TEXT NOT NULL UNIQUE,
 published_config JSONB, published_at TIMESTAMPTZ, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`);await pool.query('CREATE INDEX IF NOT EXISTS idx_stream_maker_owner ON creator_stream_maker(creator_id,updated_at DESC)');}
function register(app,{pool,requireCreatorAccount,requireCreatorAdmin,isCreatorSuiteAdmin,creatorAccessProfile,publicRuntimeIpLimiter=(req,res,next)=>next(),widgetReadLimiter=(req,res,next)=>next()}){
 const wrap=fn=>async(req,res)=>{res.set('Cache-Control','no-store');try{await fn(req,res);}catch(e){console.error('Stream Maker:',e.message);res.status(e.status||500).json({error:e.status?e.message:'Die Aktion konnte nicht abgeschlossen werden. Bitte erneut versuchen.'});}};
 const fail=(message,status=400)=>{const e=new Error(message);e.status=status;throw e;};
 const view=r=>({id:r.id,config:r.config,version:r.version,published:Boolean(r.published_config),public_token:r.public_token});
 async function own(req){const r=(await pool.query('SELECT * FROM creator_stream_maker WHERE id=$1 AND creator_id=$2',[req.params.id,req.creatorAccount.id])).rows[0];if(!r)fail('Bundle nicht gefunden.',404);return r;}
 async function validateAssets(config,owner){const urls=[config.source,...config.variants.map(x=>x.source)].filter(Boolean),tokens=[...new Set(urls.map(x=>x.split('/').pop()))];if(!tokens.length)return;const r=await pool.query('SELECT public_token FROM creator_widget_assets WHERE creator_id=$1 AND public_token=ANY($2::text[])',[owner,tokens]);if(r.rows.length!==tokens.length)fail('Ein Bild gehört nicht zu deiner Medienbibliothek. Bitte erneut hochladen.');}
 app.get('/api/creator/stream-maker',requireCreatorAccount,wrap(async(req,res)=>{const rows=await pool.query('SELECT * FROM creator_stream_maker WHERE creator_id=$1 ORDER BY updated_at DESC LIMIT 100',[req.creatorAccount.id]);res.json({bundles:rows.rows.map(view),admin:await isCreatorSuiteAdmin(req.creatorAccount)});}));
 app.post('/api/creator/stream-maker',requireCreatorAccount,wrap(async(req,res)=>{const config=M.sanitize(req.body?.config);if(!config.elements.length)fail('Füge mindestens ein Element hinzu.');await validateAssets(config,req.creatorAccount.id);const access=await creatorAccessProfile(req.creatorAccount),max=Number(access.entitlements?.max_bundles||50);const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT id FROM creator_accounts WHERE id=$1 FOR UPDATE',[req.creatorAccount.id]);const n=Number((await client.query('SELECT COUNT(*)::int AS n FROM creator_stream_maker WHERE creator_id=$1',[req.creatorAccount.id])).rows[0].n);if(n>=max)fail(`Dein Zugriff erlaubt ${max} Maker-Bundles.`,403);const row=(await client.query('INSERT INTO creator_stream_maker(id,creator_id,config,public_token) VALUES($1,$2,$3::jsonb,$4) RETURNING *',[crypto.randomUUID(),req.creatorAccount.id,JSON.stringify(config),crypto.randomBytes(24).toString('hex')])).rows[0];await client.query('COMMIT');res.status(201).json({bundle:view(row)});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
 app.put('/api/creator/stream-maker/:id',requireCreatorAccount,wrap(async(req,res)=>{const current=await own(req),config=M.sanitize(req.body?.config);if(!config.elements.length)fail('Füge mindestens ein Element hinzu.');await validateAssets(config,req.creatorAccount.id);if(!Number.isInteger(req.body?.version))fail('Versionsnummer fehlt.');const row=(await pool.query('UPDATE creator_stream_maker SET config=$3::jsonb,version=version+1,updated_at=NOW() WHERE id=$1 AND creator_id=$2 AND version=$4 RETURNING *',[current.id,req.creatorAccount.id,JSON.stringify(config),req.body?.version])).rows[0];if(!row)fail('Das Bundle wurde in einem anderen Fenster geändert. Öffne es erneut unter Meine Bundles.',409);res.json({bundle:view(row)});}));
 app.post('/api/creator/stream-maker/:id/rotate-token',requireCreatorAccount,wrap(async(req,res)=>{const current=await own(req);if(!Number.isInteger(req.body?.version))fail('Versionsnummer fehlt.');const token=crypto.randomBytes(24).toString('hex');const row=(await pool.query('UPDATE creator_stream_maker SET public_token=$3,version=version+1,updated_at=NOW() WHERE id=$1 AND creator_id=$2 AND version=$4 RETURNING *',[current.id,req.creatorAccount.id,token,req.body?.version])).rows[0];if(!row)fail('Das Bundle wurde inzwischen geändert. Bitte erneut öffnen.',409);res.json({bundle:view(row)});}));
 app.delete('/api/creator/stream-maker/:id',requireCreatorAccount,wrap(async(req,res)=>{const current=await own(req);if(!Number.isInteger(req.body?.version))fail('Versionsnummer fehlt.');const row=(await pool.query('DELETE FROM creator_stream_maker WHERE id=$1 AND creator_id=$2 AND version=$3 AND published_config IS NULL RETURNING id',[current.id,req.creatorAccount.id,req.body?.version])).rows[0];if(!row)fail('Bundle geändert oder noch im Shop veröffentlicht. Erst aus dem Shop nehmen und erneut öffnen.',409);res.json({ok:true,id:row.id});}));
 app.post('/api/creator/stream-maker/:id/control',requireCreatorAccount,wrap(async(req,res)=>{const current=await own(req),config=M.sanitize(current.config),e=config.elements.find(x=>x.id===req.body?.element);if(!e||!['start','pause','reset','plus','minus','alert'].includes(req.body?.action))fail('Ungültige Steuerung.');M.control(e,req.body?.action);const row=(await pool.query('UPDATE creator_stream_maker SET config=$3::jsonb,version=version+1,updated_at=NOW() WHERE id=$1 AND creator_id=$2 AND version=$4 RETURNING *',[current.id,req.creatorAccount.id,JSON.stringify(config),current.version])).rows[0];if(!row)fail('Gleichzeitige Änderung. Bitte erneut versuchen.',409);res.json({bundle:view(row)});}));
 app.post('/api/creator/stream-maker/:id/publish',requireCreatorAccount,requireCreatorAdmin,wrap(async(req,res)=>{const row=await own(req);if(req.body.rights_confirmed!==true)fail('Bitte bestätige die Nutzungsrechte deiner Vorlage.');const config=M.sanitize(row.config);config.elements.forEach(e=>{e.runtime={running:false,anchor:0,elapsed:0,alertUntil:0};});await pool.query('UPDATE creator_stream_maker SET published_config=$3::jsonb,published_at=NOW() WHERE id=$1 AND creator_id=$2',[row.id,req.creatorAccount.id,JSON.stringify(config)]);res.json({ok:true});}));
 app.post('/api/creator/stream-maker/:id/unpublish',requireCreatorAccount,requireCreatorAdmin,wrap(async(req,res)=>{await own(req);await pool.query('UPDATE creator_stream_maker SET published_config=NULL,published_at=NULL WHERE id=$1 AND creator_id=$2',[req.params.id,req.creatorAccount.id]);res.json({ok:true});}));
 app.get('/api/creator/stream-maker-shop',requireCreatorAccount,wrap(async(req,res)=>{const r=await pool.query('SELECT id,published_config FROM creator_stream_maker WHERE published_config IS NOT NULL ORDER BY published_at DESC LIMIT 100');res.json({templates:r.rows.map(x=>({id:x.id,config:x.published_config}))});}));
 // Taking a template creates a separate draft and copies asset ownership; edits never modify the shop source.
 app.post('/api/creator/stream-maker-shop/:id/copy',requireCreatorAccount,wrap(async(req,res)=>{const r=(await pool.query('SELECT published_config FROM creator_stream_maker WHERE id=$1 AND published_config IS NOT NULL',[req.params.id])).rows[0];if(!r)fail('Diese Vorlage ist nicht mehr verfügbar.',404);const config=M.sanitize(r.published_config);config.name+=' · Kopie';const urls=[...new Set([config.source,...config.variants.map(v=>v.source)].filter(Boolean))];
 // Reuse the normal asset upload path from the client, so quotas, signatures and ownership stay enforced.
 res.json({config,assets:urls});}));
 app.get('/api/public/stream-maker/:token',publicRuntimeIpLimiter,widgetReadLimiter,wrap(async(req,res)=>{if(!/^[a-f0-9]{48}$/.test(req.params.token))fail('Ausgabe nicht gefunden.',404);const r=(await pool.query("SELECT m.config FROM creator_stream_maker m JOIN creator_accounts c ON c.id=m.creator_id WHERE m.public_token=$1 AND c.status='active'",[req.params.token])).rows[0];if(!r)fail('Ausgabe nicht gefunden.',404);res.json({config:r.config,server_now:Date.now()});}));
}
module.exports={initialize,register};
